spring:
  data:
    mongodb:
      host: 118.25.158.194
      port: 27017
      authentication-database: test
      username: david
      password: password

  servlet:
    multipart:
      max-request-size: 500000000
      max-file-size: 50000000

server:
  tomcat:
    max-http-form-post-size: -1